-- MetaFlow DQ on Snowflake: database, warehouse and role.
-- Run once as ACCOUNTADMIN (or a role with CREATE DATABASE / WAREHOUSE).

CREATE ROLE IF NOT EXISTS METAFLOW_ROLE;
GRANT ROLE METAFLOW_ROLE TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS METAFLOW_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS METAFLOW_DQ;

GRANT USAGE ON WAREHOUSE METAFLOW_WH TO ROLE METAFLOW_ROLE;
GRANT OWNERSHIP ON DATABASE METAFLOW_DQ TO ROLE METAFLOW_ROLE COPY CURRENT GRANTS;
